Added playbook to deploy nginx with static welcome page
rattermeyer/nomad-cluster pull request #3
Opened 2017-12-20 13:53 UTC by slechte

2017-12-20 15:45 UTC, rattermeyer requested changes
Needs a few changes.... see comments ...

2017-12-20 15:45 UTC, rattermeyer commented on ansible/playbooks/nginx.yml
> +- hosts: server2
Hi,
I would not use the server name directly, but to refer to a logical group, like "webservers" defined in the inventory.
Although the group only contains one node, the playbook would stay the same, even if you then deploy for HA reasons the web server on servers 1 and 2.

2017-12-20 15:45 UTC, rattermeyer commented on ansible/playbooks/nginx.yml
> +      owner: vagrant
vagrant does not look like a good choice for a user. probably leave it out and simple set mode, so that nginx can read it.

2017-12-20 15:45 UTC, rattermeyer commented on ansible/playbooks/nginx.yml
> +      src: /vagrant/ansible/playbooks/files/index.html
you should not put an absolute path here. copy will look inside files automatically, so try it with simply index.html

2018-01-03 09:03 UTC, slechte commented
I implemented your requested changes

2018-01-04 20:53 UTC, merged